Repository dell/csi-baremetal-operator, pull requests merged in 2021-09, with the labels that each got.

#59 [ISSUE-509] Add verbose kubectl output for LVG and ACR
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
Labels: enhancement

#60 [ISSUE-512] Move TopologyID labels deletion into Operator
  pkg/node/node.go
Labels: bug

#63 [ISSUE-520] Release CSI 0.4.0-alpha
  docs/index.yaml
Labels: enhancement

#61 [ISSUE-511] Fix restoring the same node after removal
  pkg/noderemoval/delete_objects.go
Labels: bug

#65 [ISSUE-526] Release CSI 0.4.0-beta
  docs/index.yaml
Labels: enhancement

#58 [ISSUE-500] third party extenders
  api/v1/components/patcher.go
  charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
  charts/csi-baremetal-deployment/values.yaml
  docs/MANUAL_SCHEDULER_CONFIGURATION.md
  docs/README.md
  pkg/constant/platforms.go
  pkg/patcher/extender_readiness.go
  pkg/patcher/extender_readiness_test.go
  pkg/patcher/patcher_configuration.go
  pkg/patcher/scheduler_patcher.go
  pkg/scheduler_extender.go
Labels: documentation, enhancement

#66 [ISSUE-526] Bump CSI Operator version to 0.5.0
  charts/csi-baremetal-deployment/Chart.yaml
  charts/csi-baremetal-operator/Chart.yaml
  variables.mk
Labels: enhancement

#67 [ISSUE-528] update pull policy and change default tag to green
  charts/csi-baremetal-operator/values.yaml
Labels: enhancement

#68 [ISSUE-533] Update labels on CSI pods
  charts/csi-baremetal-operator/templates/manager.yaml
  pkg/common/common.go
  pkg/constant/const.go
  pkg/controller.go
  pkg/node/node_daemonset.go
  pkg/node_controller.go
  pkg/noderemoval/controller_test.go
  pkg/patcher/scheduler_patcher_vanilla.go
  pkg/scheduler_extender.go
Labels: bug

#70 [ISSUE-535] Remove outdated ACRs
  main.go
  pkg/acrvalidator/acr_validator.go
  pkg/acrvalidator/acr_validator_test.go
Labels: bug

#71 [ISSUE-538] Update node-driver-registrar sidecar
  charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
  charts/csi-baremetal-deployment/values.yaml
Labels: enhancement

#73 [ISSUE-544] code owners added
  docs/CODEOWNERS
Labels: documentation

#74 [ISSUE-553] Update CRDs apiVersion
  Makefile
  charts/csi-baremetal-deployment/templates/csidriver/csidriver.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacities.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_drives.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_nodes.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_volumes.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  deploy/csidriver/csidriver.yaml
Labels: enhancement
