Repository dell/csi-baremetal-operator, pull requests merged in 2022-02, with the labels that each got.

#107 [ISSUE-709] Improve release workflow
  .github/workflows/release.yml
Labels: enhancement

#108 [ISSUE-712] Add component labels for CSI pods
  .codecov.yml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacities.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_drives.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_nodes.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_volumes.yaml
  charts/csi-baremetal-operator/templates/manager.yaml
  pkg/common/common.go
  pkg/constant/const.go
  pkg/controller.go
  pkg/node/node_daemonset.go
  pkg/node_controller.go
  pkg/patcher/scheduler_patcher_vanilla.go
  pkg/scheduler_extender.go
Labels: bug

#111 [ISSUE-732] Pass reservation controller variables
  api/v1/components/controller.go
  charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
  charts/csi-baremetal-deployment/values.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
  pkg/controller.go
Labels: bug

#112 [ISSUE-735] update deployment instructions for GA version
  docs/README.md
Labels: documentation

#113 [ISSUE-735] update deployment instructions for GA version
  docs/README.md
Labels: documentation

#109 [ISSUE-718] Pass parameters from helm
  api/v1/components/sidecar.go
  charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
  charts/csi-baremetal-deployment/values.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
  pkg/controller.go
Labels: enhancement

#114 [ISSUE-740] Add badge with the Go Report
  docs/README.md
Labels: documentation

#115 [ISSUE-702] Bump sidecars versions
  charts/csi-baremetal-deployment/values.yaml
Labels: enhancement
