Repository dell/csi-baremetal-operator, pull requests merged in 2022-05, with the labels that each got.

#126 [ISSUE-125] Update operator documentation
  docs/MANUAL_SCHEDULER_CONFIGURATION.md
  docs/README.md
Labels: documentation, enhancement

#128 [ISSUE-847] Add new instance label
  charts/csi-baremetal-operator/templates/manager.yaml
  pkg/common/common.go
  pkg/constant/const.go
Labels: enhancement

#130 [ISSUE-853] Tokenless codecov reporting
  .github/workflows/pr.yml
Labels: bug

#121 [ISSUE-805] Upgrade from 1.0.x to 1.1.x
  Makefile
  api/v1/components/controller.go
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
  charts/csi-baremetal-operator/templates/manager.yaml
  charts/csi-baremetal-operator/templates/pre-upgrade-crds.yaml
  charts/csi-baremetal-operator/values.yaml
  docs/README.md
  hook/Dockerfile
  variables.mk
Labels: bug, enhancement
