Repository dell/csi-baremetal-operator, pull requests merged in 2022-03, with the labels that each got.

#116 [ISSUE-744]: CIS hardening support
  .codecov.yml
  .github/.codecov.yaml
  api/v1/components/controller.go
  api/v1/components/pod_security_policy.go
  api/v1/components/scheduler.go
  api/v1/components/security_context.go
  charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml
  charts/csi-baremetal-deployment/values.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_deployments.yaml
  charts/csi-baremetal-operator/templates/manager.yaml
  charts/csi-baremetal-operator/values.yaml
  controllers/deployment_controller.go
  docs/README.md
  main.go
  pkg/controller.go
  pkg/csi_deployment.go
  pkg/feature/security_verifier/error.go
  pkg/feature/security_verifier/interface.go
  pkg/feature/security_verifier/models/components.go
  pkg/feature/security_verifier/pod_security_policy.go
  pkg/feature/security_verifier/security_context_constraints.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node_controller.go
  pkg/patcher/extender_readiness_test.go
  pkg/patcher/patcher_configuration.go
  pkg/patcher/scheduler_patcher.go
  pkg/patcher/scheduler_patcher_vanilla.go
  pkg/scheduler_extender.go
  pkg/validator/rbac/error.go
Labels: documentation, enhancement

#117 [ISSUE-761] Add nodeselector option for scheduler-extender
  pkg/scheduler_extender.go
Labels: enhancement

#119 [ISSUE-719] Update supported k8s version in docs
  docs/MANUAL_SCHEDULER_CONFIGURATION.md
  docs/README.md
Labels: documentation
